Stop using django-annoying
artefactual/archivematica-fpr-admin pull request #72
Opened 2018-03-04 19:09 UTC by sevein

This closes #40.

2018-03-05 15:46 UTC, jhsimpson reviewed
I haven't tested this but from reading the code it looks good to me.  I think this is a good idea to merge.

2018-03-07 18:51 UTC, jrwdunham requested changes
I'd like to get the tests introduced here running in Travis as well as have tox or some docs explaining how to run them.

2018-03-07 18:51 UTC, jrwdunham commented on fpr/tests.py
> +    def create_fprule(self):
Nitpick: could be a func or staticmethod cuz self ain't used.

2018-03-07 18:51 UTC, jrwdunham commented on fpr/tests.py
> +import uuid
Unused import. (Is flake8 not being run on this?)

2018-03-07 18:51 UTC, jrwdunham commented on fpr/forms.py
> +            version=cleaned_data.get('version')).exists():
Nitpick: I think you should add 4 spaces indentation before lines 53 and 54 (and pylint agrees with me).

2018-03-07 18:51 UTC, jrwdunham commented on fpr/tests.py
> +                IDCommand, '12345', [])
Can you provide more detail on how to run these tests? I was unable to do so easily.

Also, looking at the definition of `get_revision_descendants` it looks like that func will not raise the exception that you are expecting to catch here. It looks like it catches that exception and just passes. 

Relatedly, I noticed that travis is not running these tests. It only runs those in testproject/. If this were fixed, then we could see if these tests were passing.

2018-03-07 18:51 UTC, jrwdunham commented on fpr/tests.py
> +    def test_fpommand_create(self):
Typo: `fpommand`

2018-03-07 22:55 UTC, sevein commented
Thanks @jrwdunham. Can you take another look?

`get_revision_descendants` raises an exception when the object cannot be found. We ignore exceptions when looking up descendants though.

2018-03-07 23:33 UTC, jrwdunham approved these changes
> get_revision_descendants raises an exception when the object cannot be found. We ignore exceptions when looking up descendants though.

Right. Oops. LGTM. 👍

2018-03-07 23:59 UTC, merged

2018-10-01 15:28 UTC, sevein commented
a62404e48118ed54c9c26457663bbbbd19f32aaf
a762136e17e8a1b981db691e21e6292557a63baa
333af7b65fd9054027d28815534dc0966831e202